<a href="https://colab.research.google.com/github/josedanielisidororeyes/Anal-tica-Descriptiva-y-Predictiva/blob/main/Clases_Anal%C3%ADtica_Predictiva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sesión 2

## Estructuras de Datos

Una lista en Python  es una colección ordenada de elementos que peude contener diferentes tipos de datos. Es uno de los tipos de datos más utilizado en python debido a su flexibilidad y facilidad de uso.

Es una estructura de datos que contiene elementos que identificas plenamente porque están dentro corchetes.

A diferencia de las tuplas, las listas tienen longitud variable y su contenido puede modificarse. Las listas son mutablea. Se pueden defirnir mediante corchetes o suando una fución list

In [2]:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
# Las listas pueden terner diferentes elemtnso
items  = ['feo', 'peekboo', 'baz', 'dwarf', 1, 2.2, False, 1]

# Se puede recuperar un elemento de la lista con el valor del índice
items[0]

'feo'

In [10]:
# Recuperando el ultimo elemento
items[-1]

1

In [12]:
items.append('Banana')
items

['feo', 'peekboo', 'baz', 'dwarf', 1, 2.2, False, 1, 'Banana']

In [13]:
print(items)

['feo', 'peekboo', 'baz', 'dwarf', 1, 2.2, False, 1, 'Banana']


In [14]:
print(items[-1]
      )

Banana


In [15]:
# Tambien se pueden insertar valores a la lista especificado el valor y la posición
items.insert(0, 'Daniel')
items

['Daniel', 'feo', 'peekboo', 'baz', 'dwarf', 1, 2.2, False, 1, 'Banana']

In [16]:
# La operación inversa a insertar es pop que elimina y devuelve un elemento particular del indice

In [18]:
# Para eliminar de la lista
items.remove('Daniel')
items

['feo', 'peekboo', 'baz', 'dwarf', 1, 2.2, False, 1, 'Banana']

In [21]:
# Se utiliza in para buscar en una lista
'Banana' in items

True

In [20]:
'Daniel' in items

False

In [22]:
'Daniel' not in items

True

In [23]:
# Concatenación y combinación de listas

In [24]:
[4, None, "foo"] +  [7, 8, (2, 3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [25]:
# Si ya tiene una lista definida, se puede agregarle varios elemento utilizando el metodo extend
items = [4, None, "foo"]
items.extend([7, 8, (2, 3)])
items

[4, None, 'foo', 7, 8, (2, 3)]

In [30]:
# Ordenar
items = [23, 4,6 ,2 ,2]
items.sort()

In [32]:
b = ['saw', 'small', 'He', 'foxes', 'six']
b.sort(key =  len)
b

['He', 'saw', 'six', 'small', 'foxes']

In [34]:
# Slicing
seq  = [7, 2, 3, 7, 5, (6, 0, 1)]
seq[2:5]

[3, 7, 5]

In [36]:
# Slicing para asignacion de valores
seq = [7, 2, 3, 7, 5, 6, 0, 1]
print(seq)
seq[3:5] =  [6, 3]
seq

[7, 2, 3, 7, 5, 6, 0, 1]


[7, 2, 3, 6, 3, 6, 0, 1]

# Tuplas
Una tupla es una secuencia inmutable de objectos de Python de longitud fija, que una vez asignada, no se puede modificar. La forma más sencilla de crearla es con una secuencia de valores separados por comas entre parentesis

In [37]:
tup = ([4, 0, 2])
tup  = tuple('string')
tup

('s', 't', 'r', 'i', 'n', 'g')

In [38]:
tup = tuple('MIAD')
tup

('M', 'I', 'A', 'D')

In [39]:
nested_tup =  (4, 5, 6), (7, 8)
print(nested_tup)
print(nested_tup[0])
print(nested_tup[1])

((4, 5, 6), (7, 8))
(4, 5, 6)
(7, 8)


# Diccionarios
El diccionario es la estructura de datos integradas más importante de Python. En otros lenguajes de programación, los diccionarios se denominan mapa hash o matrices asociativas. Un diccionario almacena una coleccion de pares clave-valor donde la clave y el valor son objectos de Python. Cada Clave está asociada a un valor para que este pueda recuperars, insertarse, modificarse o eliminarse facilmenete dada un clave especifica.


In [40]:
empty_dict =  {}
d1 =  {'a': 'some_value', 'b': [1, 2, 3, 4]}
d1

{'a': 'some_value', 'b': [1, 2, 3, 4]}

In [41]:
print(d1)
d1[7] = "an integer"

print(d1)
d1['b']

{'a': 'some_value', 'b': [1, 2, 3, 4]}
{'a': 'some_value', 'b': [1, 2, 3, 4], 7: 'an integer'}


[1, 2, 3, 4]

In [42]:
resultados = {'tpr': 67.9, "tnr": 90, 'acc': .5}
print(resultados)

{'tpr': 67.9, 'tnr': 90, 'acc': 0.5}


In [43]:
del d1['a']

In [44]:
d1

{'b': [1, 2, 3, 4], 7: 'an integer'}

In [45]:
list(d1.keys())

['b', 7]

In [46]:
list(d1.values())

[[1, 2, 3, 4], 'an integer']

In [47]:
list(d1.items())

[('b', [1, 2, 3, 4]), (7, 'an integer')]

In [48]:
d1.update({'b': 'foo', 'c': 'daniel'}
          )
d1

{'b': 'foo', 7: 'an integer', 'c': 'daniel'}

## Manejo de Datos Números con Numpy

Numpy (Numerical Python) es una biblioteca fundamental para la computación cientifica en Python. Proporciona soporte para manejar operaciones vectorizadas.

In [51]:
print(dir(np))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_core', '_distributor_init', '_expired_attrs_2_0', '_get_promotion_state', '_globals', '_int_extended_msg', '_mat', '_msg', '_no_nep50_warning', '_pyinstaller_hooks_dir', '_pytesttester', '_set_promotion_state', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'arra

In [54]:
# Creación de Arrays
# np.array()
# Arreglos con valores inicializados autoaticamente con ceros, aleatorios, etc.}
arr =  np.array(42)
print("El arreglo de 0-dimensiones", arr)

El arreglo de 0-dimensiones 42


In [57]:
# Arreglo de 1d
arr =  np.array([1, 2, 3,  4, 5])
print("Arreglo en 1 dimensiones", arr)

Arreglo en 1 dimensiones [1 2 3 4 5]


In [61]:
array_zeros =  np.zeros((3, 4))
print("Aray 4x3 lleno de ceros", array_zeros)

Aray 4x3 lleno de ceros [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [63]:
array_intrand =  np.random.randint(0, 51, 10)
print("Array de 10 elementos aleatorios ", array_intrand)

Array de 10 elementos aleatorios  [45 49 38 10  2 23 12  5  1 34]


In [64]:
array_lista = np.empty((2, 2))
print("Lista vacia", array_lista)

Lista vacia [[6.13789288e-316 0.00000000e+000]
 [2.31274374e-152 7.07909259e+194]]


In [65]:
# Linespace inicial , valorfinal, numero de valores
array_linspace =  np.linspace(0, 1, 5)
print("Crea un array con numeros distribuidos uniformamente")
print(array_linspace)

Crea un array con numeros distribuidos uniformamente
[0.   0.25 0.5  0.75 1.  ]


In [67]:
array_binom = np.random.binomial(n = 10, p = 0.5, size = (3, 3))
print(array_binom)

[[6 5 7]
 [4 3 4]
 [4 3 4]]


In [68]:
array_identidad =  np.eye(4)
print("Array identidad 4x4")
print(array_identidad)

Array identidad 4x4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [49]:
import numpy as np
import time

# Datos de ejemplo
x   =  np.arange(1_000_000)

# Con bucle tradicional
inicio =  time.time()
resultado_bucle  =  []
for valor in x:
  resultado_bucle.append(valor  ** 2)
fin =  time.time()

print('Tiempo con bucle: ', fin - inicio, "Segundo")

Tiempo con bucle:  0.2319333553314209 Segundo


In [74]:
inicio =  time.time()
resultado_vectorizado =  x ** 2 # Operación directa sobre el todo el array
fin =  time.time()
print("Tiempo con vectorización: ", fin - inicio, "Segundos")

Tiempo con vectorización:  0.005791187286376953 Segundos


## Propiedades de un ndarray


In [73]:
array_1d =  np.array([1, 2, 3])
print("Arrat 1D:", array_1d)
print("Forma: ", array_1d.shape)
print("Tamaño", array_1d.size)
print("Tipo de datos", array_1d.dtype)

Arrat 1D: [1 2 3]
Forma:  (3,)
Tamaño 3
Tipo de datos int64


# indexación y Segmentación/Corte

In [75]:
array_1d =  np.array([10, 20, 30, 40, 50])
print(array_1d[0])
print(array_1d[3])

10
40


In [80]:
# Array bindimencional
array_2d =  np.array([[1, 2, 3], [4, 5, 6], [4, 8, 9]])
print(array_2d[1, 2])
print(array_2d[1, 0])

6
4


In [81]:
print(array_1d[array_1d > 10])

[20 30 40 50]


In [86]:
# Las operaciones se realizan elemento a elemento
array_1d + 100

array([110, 120, 130, 140, 150])

In [84]:
array_1d/100

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [85]:
array_1d * 2

array([ 20,  40,  60,  80, 100])

# Operaciones Universales

In [87]:
np.sqrt(array_1d)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [88]:
np.sin(array_1d)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [89]:
np.log(array_1d)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

In [90]:
np.mean(array_1d)

np.float64(30.0)

In [91]:
 np.max(array_1d)

np.int64(50)

In [92]:
np.min(array_1d)

np.int64(10)