<a href="https://colab.research.google.com/github/josedanielisidororeyes/Anal-tica-Descriptiva-y-Predictiva/blob/main/Practica_4_Manipulaci%C3%B3n_de_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import random
# Semillas para replicar resultados
random.seed(5)       # Para random de Python
np.random.seed(5)    # Para NumPy

# Crea 2 matrices 3x3 con números aleatorios entre 1 y 10
print("Matrix A")
matrix_a = np.random.randint(1, 11, size = (3, 3))
print(matrix_a)
print()
print("Matrix B")
matrix_b =  np.random.randint(1, 10,  size  =  (3, 3))
print(matrix_b)
print()

# Suma de matrices
print("La suma de las matrices A y B es:")
print(matrix_a +  matrix_b)
print('\n')

# Resta de matrices
print("La resta de B de A es:")
print(matrix_a -  matrix_b)
print()

# 2  x  Matrix A
print("Multiplica la primer matriz por 2")
print(matrix_a *  2)
print()

# Producto Matriicial
print("Realiza una multiplicación matricial entre matrices")
print(np.dot(matrix_a, matrix_b))
print()

Matrix A
[[ 4  7  7]
 [ 1 10  9]
 [ 5  8  1]]

Matrix B
[[1 8 2]
 [6 8 1]
 [2 5 7]]

La suma de las matrices A y B es:
[[ 5 15  9]
 [ 7 18 10]
 [ 7 13  8]]


La resta de B de A es:
[[ 3 -1  5]
 [-5  2  8]
 [ 3  3 -6]]

Multiplica la primer matriz por 2
[[ 8 14 14]
 [ 2 20 18]
 [10 16  2]]

Realiza una multiplicación matricial entre matrices
[[ 60 123  64]
 [ 79 133  75]
 [ 55 109  25]]

